### ISSUE TITLE
:sparkles: **Edit album** :sparkles:

### ISSUE THREAD

**Issue by joaojdacosta** [joaojdacosta/getstarted-codeigniter#4]
Tasks:
- [ ] Actualizar a interface com o link que permite editar um determinado álbum 
- [ ] Implementar a funcionalidade que permite editar o álbum

**Comment by Aderito-Pedro** [comment]
Dr. Costa tenho uma dúvida "Atualizar uma interface com o link que permite editar um determinado álbum", o album se refere especificamente em que!?

**Comment by Aderito-Pedro** [comment]
Já entende Dr...
